# {{ENV}}/kustomization.yaml

# helm gitops render-env -e {{ENV}} -r {{REMOTE_HELM_CHART_REPO}} -t {{REMOTE_HELM_CHART_TAG}}

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rendered/helm/helm-chart.yaml

# patchesStrategicMerge:
#   - patch.yaml