# {{ENV}}/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: '{{CHART_NAME}}'
  repo: '{{REMOTE_HELM_CHART_REPO}}'
  version: '{{REMOTE_HELM_CHART_TAG}}'
  releaseName: '{{ENV}}'
  valuesFile: values.yaml

patchesStrategicMerge:
  - patch.yaml